title: Asset Share Commons EDS
description: A production-ready AEM Edge Delivery Services front-end for digital asset search, preview, download, and sharing.
baseurl: ""
url: "https://davidjgonzalez.github.io/asset-share-commons-eds"
github_repo: "https://github.com/davidjgonzalez/asset-share-commons-eds"

theme: null
plugins:
  - jekyll-seo-tag

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.md"
    values:
      layout: "home"

sass:
  sass_dir: assets/css
  style: compressed
