/**
 * board-item — default renderer for an asset item on the board/collection canvas.
 *
 * Swap in your own by setting `configurations.board.itemRenderer` to a function with
 * this same signature — items don't have to look like the default card at all. It must
 * return a single root element as an HTML string, carrying the attributes/classes the
 * board's interaction code depends on:
 *
 *   - `data-asc-asset="<uuid>"` on the root element — required for drag, click-to-open,
 *     rubber-band selection, and the minimap.
 *   - `style="left: Xpx; top: Ypx"` on the root element — required initial position;
 *     `item.x`/`item.y` when set, otherwise fall back to a default grid position.
 *   - `.board__item` class on the root element — required for drag/selection/search to
 *     find it (in addition to whatever your own root class is).
 *   - Remove button: `<button class="board__item-remove" data-asc-asset="<uuid>">` —
 *     only when `config.mode === 'interactive'`.
 *   - Notes button: `<button class="board__notes-btn" data-asc-asset="<uuid>">` — only
 *     when `config.mode === 'interactive' && config.notes`; add `.board__item--has-note`
 *     to the root when `item.notes` is set, so the button's "has a note" style applies.
 *   - `data-asc-notes="<text>"` on the root whenever `config.notes` — required (in both
 *     interactive and view-only/read-only modes) for the hover-preview popover to read
 *     the note text from.
 *   - Optional `.asc-ui-corner-ribbon` element (e.g. `<span class="asc-ui-corner-ribbon">
 *     Notes</span>`) when the item has a note — the default renders one to flag it
 *     visually; purely decorative, so mark it `aria-hidden="true"`.
 *   - Optional `data-filter="<lowercase search text>"` on the root — required only if
 *     you want the board's search box (`search-properties` config) to match this item.
 *
 * @param {{ asset: Asset, notes?: string, x?: number, y?: number }} item
 * @param {number} index  Position in the render list — used for the default grid layout
 *   when `item.x`/`item.y` are unset.
 * @param {object} config  The board block's parsed config (see blocks/board/board.js
 *   parseConfig): { mode, notes, searchProperties, ... }.
 * @returns {string} A single root element as an HTML string.
 */
import services from './core/services/services.js';
import { escHtml, escAttr } from './html.js';

const ICONS = {
  close: '&times;',
  download: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',
  copyUrl: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="17 8 12 3 7 8"/><line x1="12" y1="3" x2="12" y2="15"/></svg>',
  notes: '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 15a4 4 0 0 1-4 4H8l-5 3v-3a4 4 0 0 1-2-3.46V7a4 4 0 0 1 4-4h12a4 4 0 0 1 4 4z"/></svg>',
};

function buildSearchStr(asset, config) {
  if (!config.searchProperties.length) return '';
  return config.searchProperties.map((prop) => asset.getProperty(prop).text).join(' ').toLowerCase().trim();
}

/**
 * Preview image for the board — deliberately NOT the "thumbnail" rendition ladder
 * (services.renditions.getThumbnailUrl/getThumbnailSrcset): thumbnails are generated by
 * AEM's DAM processing as a fixed-size square crop, which is exactly what --natural is
 * trying to avoid. "web" (falls back to "original") is a resize-to-fit rendition that
 * preserves the asset's real aspect ratio, so the card's shape actually varies by asset.
 * Non-image assets (PDF, video, doc) fall back to the thumbnail system, since those don't
 * have a "web" image rendition to begin with.
 */
function resolvePreviewImage(asset) {
  const rendition = asset.getRendition('web') || asset.getRendition('original');
  if (rendition?.mimeType?.startsWith('image/') && rendition.url) {
    return { url: rendition.url, width: rendition.width || null, height: rendition.height || null };
  }
  return { url: services.renditions.getThumbnailUrl(asset), width: null, height: null };
}

export default function boardItemHtml(item, index, config) {
  const { asset, notes: itemNotes } = item;
  const x = item.x !== undefined ? item.x : 80 + (index % 8) * 260;
  const y = item.y !== undefined ? item.y : 80 + Math.floor(index / 8) * 220;
  const preview = resolvePreviewImage(asset);
  const searchStr = buildSearchStr(asset, config);
  const interactive = config.mode === 'interactive';
  const showNotes = config.notes;

  // A board item is just a preview: no title/meta body, no footer — the thumb shows the
  // image at its own native aspect ratio (asc-ui-asset-card--natural), never cropped.
  return `
    <article class="asc-ui-asset-card asc-ui-asset-card--natural board__item${showNotes && itemNotes ? ' board__item--has-note' : ''}"
             style="left: ${x}px; top: ${y}px"
             role="button"
             tabindex="0"
             aria-label="${escAttr(asset.title)}"
             data-asc-asset="${escAttr(asset.uuid)}"
             ${searchStr ? `data-filter="${escAttr(searchStr)}"` : ''}
             ${showNotes ? `data-asc-notes="${escAttr(itemNotes || '')}"` : ''}>
      <div class="asc-ui-asset-card__thumb">
        ${interactive ? `
        <div class="asc-ui-asset-card__overlay">
          <button type="button"
                  class="asc-ui-icon-btn board__item-remove"
                  data-asc-asset="${escAttr(asset.uuid)}"
            aria-label="Remove ${escHtml(asset.title)} from collection">${ICONS.close}</button>
        </div>` : ''}
        <div class="asc-ui-asset-card__overlay asc-ui-asset-card__overlay--bottom board__rendition-actions">
          <button type="button" class="asc-ui-icon-btn board__rendition-action"
            data-board-action="download" data-asc-asset="${escAttr(asset.uuid)}"
            aria-haspopup="true" aria-expanded="false" aria-label="Download rendition" title="Download">${ICONS.download}</button>
          <button type="button" class="asc-ui-icon-btn board__rendition-action"
            data-board-action="copy-url" data-asc-asset="${escAttr(asset.uuid)}"
            aria-haspopup="true" aria-expanded="false" aria-label="Copy rendition URL" title="Copy URL">${ICONS.copyUrl}</button>
        </div>
        ${interactive && showNotes ? `
        <div class="asc-ui-asset-card__overlay asc-ui-asset-card__overlay--bottom board__notes-overlay">
          <button type="button"
                  class="asc-ui-icon-btn board__notes-btn"
                  data-asc-asset="${escAttr(asset.uuid)}"
                  aria-label="Add or edit note"
            title="Add or edit note">${ICONS.notes}</button>
        </div>` : ''}
        ${!interactive && showNotes && itemNotes ? `
        <div class="asc-ui-asset-card__overlay asc-ui-asset-card__overlay--bottom board__notes-overlay" aria-hidden="true">
          <span class="asc-ui-icon-btn board__notes-btn">${ICONS.notes}</span>
        </div>` : ''}
        <img src="${escAttr(preview.url)}"${preview.width && preview.height ? ` width="${preview.width}" height="${preview.height}"` : ''} alt="${escHtml(asset.description || asset.title || asset.name || '')}" loading="lazy" draggable="false">
      </div>
    </article>`;
}
